native PF_RING support with fixes

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -277,6 +277,13 @@ AC_INIT(configure.in)
 
 # libpfring (currently only supported for libpcap enabled pfring)
 # Error on the side of caution. If libpfring enabled pcap is being used and we don't link against -lpfring compilation will fail.
+    AC_ARG_ENABLE(pfring,
+            [  --enable-pfring  Enable Native PF_RING support],
+            [ enable_pfring=yes
+            ])
+    if test "$enable_pfring" = "yes"; then
+    CFLAGS="$CFLAGS -DHAVE_PFRING"
+    fi
     AC_ARG_WITH(libpfring_includes,
             [  --with-libpfring-includes=DIR  libpfring include directory],
             [with_libpfring_includes="$withval"],[with_libpfring_includes=no])
@@ -294,6 +301,15 @@ AC_INIT(configure.in)
 
     LIBPFRING=""
     AC_CHECK_LIB(pfring, pfring_open,, LIBPFRING="no")
+    if test "$LIBPFRING" = "no"; then
+        if test "enable_pfring" = "yes"; then
+        echo
+        echo "   ERROR! --enable-pfring was passed but the library was not found, go get it"
+        echo "   from http://www.ntop.org/PF_RING.html"
+        echo
+        exit 1
+        fi
+    fi
 
 # libpcap
     AC_ARG_WITH(libpcap_includes,
