Initial Napatech support by Randy Caldejon / nPulse.

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -1042,6 +1042,48 @@ AC_CHECK_HEADER(pcap.h,,[AC_ERROR(pcap.h not found ...)])
         exit 1
     fi
 
+# Check for Napatech support.
+
+    AC_ARG_ENABLE(napatech,
+                [  --enable-napatech  Enable Napatech adapter],
+                [ enable_napatech=yes ],
+                [ enable_napatech=no])
+    AC_ARG_WITH(napatech_includes,
+            [  --with-napatech-includes=DIR  napatech include directory],
+            [with_napatech_includes="$withval"],[with_napatech_includes="no"])
+    AC_ARG_WITH(napatech_libraries,
+            [  --with-napatech-libraries=DIR  napatech library directory],
+            [with_napatech_libraries="$withval"],[with_napatech_libraries="no"])
+
+    if test "$enable_napatech" = "yes"; then
+
+        if test "$with_napatech_includes" != "no"; then
+            CPPFLAGS="${CPPFLAGS} -I${with_napatech_includes}"
+        fi
+
+        if test "$with_napatech_libraries" != "no"; then
+            LDFLAGS="${LDFLAGS} -L${with_napatech_libraries} -lntfeeds -lntcommoninterface"
+        fi
+
+        AC_CHECK_HEADER(ntfeeds.h,NAPATECH="yes",NAPATECH="no")
+        if test "$NAPATECH" != "no"; then
+            NAPATECH=""
+            AC_CHECK_LIB(ntcommoninterface,NTCI_OpenCard,NAPATECH="yes",NAPATECH="no")
+#AC_CHECK_LIB(ntfeeds,napatech_open,NAPATECH="yes",NAPATECH="no")
+        fi
+
+        if test "$NAPATECH" != "no"; then
+            CFLAGS="${CFLAGS} -DHAVE_NAPATECH"
+        fi
+
+        if test "$NAPATECH" = "no"; then
+            echo
+            echo "  ERROR! libntfeeds (and libntcommoninterface) library not found"
+            echo
+            exit 1
+        fi
+    fi
+
 # get revision
     if test -f ./revision; then
         REVISION=`cat ./revision`
@@ -1078,6 +1120,7 @@ Suricata Configuration:
   Debug validation enabled: ${enable_debug_validation}
   CUDA enabled:             ${enable_cuda}
   DAG enabled:              ${enable_dag}
+  Napatech enabled:         ${enable_napatech}
   Profiling enabled:        ${enable_profiling}
   GCC Protect enabled:      ${enable_gccprotect}
   GCC march native enabled: ${enable_gccmarch_native}
