github-ci: check for duplicate SIDs in rules/

diff --git a/.github/workflows/builds.yml b/.github/workflows/builds.yml
--- a/.github/workflows/builds.yml
+++ b/.github/workflows/builds.yml
@@ -116,6 +116,15 @@ jobs:
 
       - uses: actions/checkout@v2
 
+      # Prebuild check for duplicat SIDs
+      - name: Check for duplicate SIDs
+        run: |
+          dups=$(sed -n 's/^alert.*sid:\([[:digit:]]*\);.*/\1/p' ./rules/*.rules|sort|uniq -d|tr '\n' ' ')
+          if [[ "${dups}" != "" ]]; then
+            echo "::error::Duplicate SIDs found:${dups}"
+            exit 1
+          fi
+
       # Download and extract dependency archives created during prep
       # job.
       - uses: actions/download-artifact@v2
