github-ci: fail if cargo clippy --fix creates a changes
Previously this was doing fixups and only warning, not erroring. Which
could made the following clippy command pass.

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -71,7 +71,8 @@ jobs:
       - run: |
           diff=$(git diff)
           if [ "${diff}" ]; then
-              echo "::warning ::Clippy --fix made changes, please fix"
+              echo "::error ::Clippy --fix made changes, please fix"
+              exit 1
           fi
       - run: cargo clippy --all-features
         working-directory: rust
